const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function setup(replies={},preferences=null){
 const storage=new Map(preferences?[['sector-pulse:delta-ui-v1',JSON.stringify(preferences)]]:[]);
 const nodes=new Map(),calls=[];let html='',chartOptions;
 function node(id){if(!nodes.has(id))nodes.set(id,{value:'',disabled:false,textContent:'',style:{},events:{},classList:{contains:()=>false},addEventListener(n,f){this.events[n]=f},replaceChildren(){},append(){},add(){},insertAdjacentHTML(pos,s){html+=s}});return nodes.get(id)}
 const status={submit_strategy_managed:true,credentials:'MISSING',authentication:'MISSING',live_gate_enabled:true,running:false,paper:{trades:[],position:null},orders:[],runner:{message:'Stopped'}};
 const context={localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},window:{EmaCloudChart:{mount:(container,options)=>{chartOptions=options;return {update(){},healthy(){},error(){}}}}},Option:function(t,v){this.text=t;this.value=v},document:{querySelector:node,getElementById:node,head:{append(){}},createElement:()=>node(Math.random())},setInterval(){},crypto:{randomUUID:()=> 'uuid-123456789'},URLSearchParams,fetch:async(url,opts)=>{calls.push({url,body:opts?.body?JSON.parse(opts.body):undefined});if(url.endsWith('runner-stop'))status.running=false;return {ok:!replies[url]?.error,json:async()=>replies[url] || (url.endsWith('status')?status:{status:'closed',filled_contracts:1})}}};
 vm.runInNewContext(fs.readFileSync('delta-india.js','utf8'),context);context.window.DeltaIndiaWorkspace.mount('other');
 for(const [k,v] of Object.entries({'workflow':'LIVE','symbol':'BTCUSD','side':'buy','contracts':'3','price':'84250','tif':'ioc','reduce':'false','timeframe':'5m','rsi':'14','ma-length':'14','ma':'SMA','direction':'BOTH'}))node('delta-'+k).value=v;
 return {node,calls,html,status,storage,getChartOptions:()=>chartOptions};
}
test('LIVE Submit transmits selected RSI gate settings with exact native ticket terms',async()=>{const s=setup();await s.node('delta-submit').events.click();const submitted=s.calls.filter(c=>c.url.endsWith('/submit'));assert.equal(submitted.length,1);assert.equal(submitted[0].body.mode,'LIVE');assert.equal(submitted[0].body.contracts,3);assert.equal(submitted[0].body.limit_price,'84250');assert.equal(submitted[0].body.request_id,'uuid-123456789');assert.ok(!s.calls.some(c=>/preview|verify|confirm/.test(c.url)));});
test('runner start transmits exact selected strategy and does not automatically start at mount',async()=>{const s=setup();assert.equal(s.calls.length,0);await s.node('delta-start').events.click();assert.equal(s.calls[0].url,'/api/delta-india/runner-start');assert.equal(s.calls[0].body.resolution,'5m');assert.equal(s.calls[0].body.direction,'BOTH');});
test('connection fields are masked and cleared; preferences never store credentials',async()=>{const s=setup();s.node('delta-key').value='fake-existing-key';s.node('delta-secret').value='fake-existing-secret';await s.node('delta-connect').events.click();assert.equal(s.node('delta-secret').value,'');assert.equal(s.calls[0].url,'/api/delta-india/connect');assert.ok(s.html.includes('type="password"'));s.node('delta-workflow').events.change();assert.ok(!JSON.stringify([...s.storage.values()]).includes('fake-existing'));});
test('order ticket precedes chart, has quantity and direct actions with responsive status',()=>{const s=setup();assert.ok(s.html.indexOf('id="delta-ticket-panel"')<s.html.indexOf('id="delta-chart"'));for(const label of ['Quantity · contracts','Submit Order','Start Runner','Connection settings'])assert.ok(s.html.includes(label));assert.ok(!/Review|Confirm|Prepare/.test(s.html));});
test('switching workflow retains matching market data while an async refresh finishes',()=>{const s=setup();s.node('delta-bid').textContent='84250 USD';s.node('delta-ask').textContent='84250.5 USD';s.node('delta-workflow').events.change();assert.equal(s.node('delta-bid').textContent,'84250 USD');assert.equal(s.node('delta-ask').textContent,'84250.5 USD');});
test('optional runner trailing transmits selected settings directly on Start',async()=>{const s=setup();s.node('delta-trailing-enabled').checked=true;s.node('delta-trailing-mode').value='POINTS';s.node('delta-trailing-step').value='50';await s.node('delta-start').events.click();assert.equal(s.calls[0].body.trailing_enabled,true);assert.equal(s.calls[0].body.trailing_mode,'POINTS');assert.equal(s.calls[0].body.trailing_step,50);});
test('trailing off disables step inputs and native split preview adapts to quantity',()=>{const s=setup();s.node('delta-trailing-enabled').checked=false;s.node('delta-trailing-enabled').events.change();assert.equal(s.node('delta-trailing-mode').disabled,true);assert.equal(s.node('delta-trailing-step').disabled,true);s.node('delta-trailing-enabled').checked=true;s.node('delta-trailing-mode').value='PERCENTAGE';s.node('delta-trailing-step').value='10';s.node('delta-contracts').value='4';s.node('delta-trailing-enabled').events.change();assert.match(s.node('delta-trailing-preview').textContent,/1 \/ 1 \/ 2/);assert.equal(s.node('delta-trailing-mode').disabled,false);s.node('delta-contracts').value='2';s.node('delta-contracts').events.change();assert.match(s.node('delta-trailing-preview').textContent,/1 \/ 0 \/ 1/);assert.ok(s.html.includes('id="delta-trailing-enabled" type="checkbox">'));});

test('market ticket omits price, fixes IOC and restores limit controls',async()=>{const s=setup();s.node('delta-tif').value='gtc';s.node('delta-order-type').value='market_order';s.node('delta-order-type').events.change();assert.equal(s.node('delta-price-field').hidden,true);assert.equal(s.node('delta-price').disabled,true);assert.equal(s.node('delta-tif').disabled,true);await s.node('delta-submit').events.click();const body=s.calls.find(c=>c.url.endsWith('/submit')).body;assert.equal(body.order_type,'market_order');assert.equal(body.time_in_force,'ioc');assert.ok(!('limit_price' in body));s.node('delta-order-type').value='limit_order';s.node('delta-order-type').events.change();assert.equal(s.node('delta-tif').value,'gtc');assert.equal(s.node('delta-price-field').hidden,false);assert.equal(s.node('delta-price').disabled,false);assert.equal(s.node('delta-tif').disabled,false);assert.ok(s.html.includes('value="market_order"'));});

test('chart Sell buys resolved put with shared market settings; chart Buy buys call',async()=>{
 const replies={'/api/delta-india/instruments':{instruments:[{symbol:'BTCUSD',contract_type:'perpetual_futures'}],available_types:[],supported_live_count:1,listed_count:1}};
 const chart={product:{symbol:'BTCUSD'},timeframe:'5m',candles:[],last_completed:null,fetched_at:1};
 replies['/api/delta-india/chart?symbol=BTCUSD&resolution=5m&rsi_length=14&ma_length=14&ma_type=SMA']=chart;
 replies['/api/delta-india/quote?symbol=BTCUSD']={bid:100,ask:101,exchange_at:1};
 for(const d of ['BUY','SELL'])replies['/api/delta-india/chart-option?symbol=BTCUSD&direction='+d]={symbol:d==='BUY'?'C-BTC-100':'P-BTC-100',strike:'100',expiry:1000};
 const s=setup(replies);s.node('delta-order-type').value='market_order';await s.node('delta-refresh').events.click();assert.match(s.node('delta-chart-route').textContent,/P-BTC-100/,s.node('delta-message').textContent);
 for(const [id,symbol] of [['chart-sell','P-BTC-100'],['chart-buy','C-BTC-100']]){await s.node('delta-'+id).events.click();const body=s.calls.filter(c=>c.url.endsWith('/submit')).at(-1).body;assert.equal(body.symbol,symbol);assert.equal(body.side,'buy');assert.equal(body.reduce_only,false);assert.equal(body.contracts,3);assert.equal(body.order_type,'market_order');assert.equal(body.chart_symbol,'BTCUSD');}
 s.node('delta-symbol').events.change();await s.node('delta-chart-buy').events.click();assert.equal(s.calls.filter(c=>c.url.endsWith('/submit')).length,2);
 assert.match(s.node('delta-chart-route').textContent,/Refresh/);
});

test('indicator EMA selection synchronizes strategy settings and re-fetches without submitting',async()=>{
 const chart={product:{symbol:'BTCUSD',tick_size:'0.5'},timeframe:'5m',candles:[],last_completed:null,fetched_at:1};
 const replies={'/api/delta-india/instruments':{instruments:[{symbol:'BTCUSD',contract_type:'perpetual_futures'}],available_types:[],supported_live_count:1,listed_count:1},'/api/delta-india/quote?symbol=BTCUSD':{bid:100,ask:101,exchange_at:1}};
 for(const suffix of ['ma_length=14&ma_type=SMA','ma_length=9&ma_type=EMA'])replies['/api/delta-india/chart?symbol=BTCUSD&resolution=5m&rsi_length=14&'+suffix]=chart;
 for(const d of ['BUY','SELL'])replies['/api/delta-india/chart-option?symbol=BTCUSD&direction='+d]={symbol:d==='BUY'?'C-BTC-100':'P-BTC-100',strike:'100',expiry:1000};
 const s=setup(replies);await s.node('delta-refresh').events.click();s.getChartOptions().onRsiSettingsChange({maType:'EMA',maLength:9});await new Promise(r=>setImmediate(r));assert.equal(s.node('delta-ma').value,'EMA');assert.equal(s.node('delta-ma-length').value,'9');assert.ok(s.calls.some(c=>c.url.includes('ma_length=9&ma_type=EMA')));assert.equal(s.calls.filter(c=>/submit|start/.test(c.url)).length,0);
});

test('manual Submit refuses unavailable backend capability without sending a paper/live entry',async()=>{const s=setup({'/api/delta-india/status':{credentials:'MISSING',running:false,paper:{trades:[]},runner:{message:'Stopped'},orders:[]}});await s.node('delta-submit').events.click();assert.match(s.node('delta-message').textContent,/pending backend deployment/);assert.equal(s.calls.filter(c=>c.url.endsWith('/submit')||c.url.endsWith('/paper-preview')).length,0);});

test('unmet strategy condition remains visible and paper record is never called',async()=>{const s=setup({'/api/delta-india/paper-preview':{error:'Strategy condition not met: a fresh completed bullish RSI crossover is required; no order submitted.'}});s.node('delta-workflow').value='PAPER';await s.node('delta-submit').events.click();assert.match(s.node('delta-message').textContent,/Strategy condition not met/);assert.equal(s.calls.filter(c=>c.url.endsWith('/paper-record')||c.url.endsWith('/runner-start')).length,0);const ticket=s.calls.find(c=>c.url.endsWith('/paper-preview')).body;assert.equal(ticket.ma_type,'SMA');assert.equal(ticket.rsi_length,14);assert.equal(ticket.symbol,'BTCUSD');});

function marketReplies(){const chart={product:{symbol:'BTCUSD',tick_size:'0.5'},timeframe:'5m',candles:[],last_completed:null,fetched_at:1};const r={'/api/delta-india/instruments':{instruments:[{symbol:'BTCUSD',contract_type:'perpetual_futures'}],available_types:[],supported_live_count:1,listed_count:1},'/api/delta-india/quote?symbol=BTCUSD':{bid:100,ask:101,exchange_at:1}};for(const ma of ['SMA','EMA'])r['/api/delta-india/chart?symbol=BTCUSD&resolution=5m&rsi_length=14&ma_length=14&ma_type='+ma]=chart;return r;}
test('Stop response re-enables valid Paper Start/Submit immediately; read-only remains visibly disabled',async()=>{const s=setup(marketReplies());s.status.running=true;s.node('delta-workflow').value='PAPER';await s.node('delta-refresh').events.click();assert.equal(s.node('delta-start').disabled,true);assert.equal(s.node('delta-submit').disabled,true);await s.node('delta-stop').events.click();assert.equal(s.node('delta-start').disabled,false);assert.equal(s.node('delta-submit').disabled,false);assert.match(s.node('delta-control-state').textContent,/Runner stopped/);s.node('delta-workflow').value='READ_ONLY';s.node('delta-workflow').events.change();assert.equal(s.node('delta-start').disabled,true);assert.equal(s.node('delta-submit').disabled,true);assert.match(s.node('delta-control-state').textContent,/Read-only/);assert.equal(s.calls.filter(c=>c.url.endsWith('/runner-start')||c.url.endsWith('/submit')).length,0);});
test('Paper display preferences survive reload, live workflow never restores automatically',async()=>{for(const mode of ['PAPER','LIVE']){const s=setup(marketReplies(),{workflow:mode,symbol:'BTCUSD',timeframe:'5m',rsi:'14',ma:'EMA','ma-length':'14',contracts:'10','order-type':'market_order','trailing-enabled':true,'trailing-mode':'PERCENTAGE','trailing-step':'5'});await s.node('delta-refresh').events.click();assert.equal(s.node('delta-workflow').value,mode==='PAPER'?'PAPER':'READ_ONLY');assert.equal(s.node('delta-ma').value,'EMA');assert.equal(s.node('delta-contracts').value,'10');assert.equal(s.node('delta-order-type').value,'market_order');assert.equal(s.node('delta-trailing-enabled').checked,true);assert.equal(s.calls.filter(c=>c.url.endsWith('/runner-start')||c.url.endsWith('/submit')).length,0);assert.ok(!JSON.stringify([...s.storage.values()]).includes('secret'));}});

test('ATM runner is capability gated and never silently starts a legacy futures strategy',async()=>{
 const s=setup();s.node('delta-strategy-mode').value='ATM_OPTIONS';await s.node('delta-refresh').events.click();const before=s.calls.filter(c=>c.url.endsWith('runner-start')).length;await s.node('delta-start').events.click();assert.equal(s.calls.filter(c=>c.url.endsWith('runner-start')).length,before);assert.match(s.node('delta-message').textContent,/awaits backend deployment/);
});
test('explicit ATM runner Start sends option execution mode with ten contracts and underlying signal settings',async()=>{
 const s=setup();s.status.atm_options_strategy=true;s.node('delta-strategy-mode').value='ATM_OPTIONS';s.node('delta-contracts').value='10';await s.node('delta-refresh').events.click();await s.node('delta-start').events.click();const call=s.calls.find(c=>c.url.endsWith('runner-start'));assert.ok(call);assert.equal(call.body.strategy_mode,'ATM_OPTIONS');assert.equal(call.body.symbol,'BTCUSD');assert.equal(call.body.contracts,10);
});
