const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(){const context={window:{},setTimeout,clearTimeout};vm.runInNewContext(fs.readFileSync('delta-india.js','utf8'),context);let time=1800000;const tasks=new Map(),sockets=[],output=[],health=[];let id=0;
 class Socket{constructor(url){this.url=url;this.readyState=0;this.sent=[];sockets.push(this);}send(x){this.sent.push(JSON.parse(x));}close(){this.readyState=3;this.onclose?.();}open(){this.readyState=1;this.onopen();}emit(m){this.onmessage({data:JSON.stringify(m)});}}
 const timer=(f,d)=>{const n=++id;tasks.set(n,{f,at:time+d});return n;},advance=ms=>{const end=time+ms;while(true){const next=[...tasks].sort((a,b)=>a[1].at-b[1].at)[0];if(!next||next[1].at>end)break;time=next[1].at;tasks.delete(next[0]);next[1].f();}time=end;};let recoveries=0;
 const history=[{timestamp:1200,open:10,high:12,low:9,close:11,volume:4},{timestamp:1500,open:11,high:13,low:10,close:12,volume:5}];
 const feed=context.window.DeltaPublicStream.create({symbol:'BTCUSD',resolution:'5m',history,Socket,now:()=>time,timer,cancel:x=>tasks.delete(x),recover:async()=>{recoveries++;return {candles:history}},onUpdate:d=>output.push(d),onHealth:h=>health.push(h)});
 return {feed,sockets,output,health,advance,tasks,get time(){return time},get recoveries(){return recoveries}};}
test('India channels, ordered quotes and latest forming revision without duplicate rows',async()=>{const s=setup(),ws=s.sockets[0];ws.open();await new Promise(setImmediate);assert.equal(ws.url,'wss://public-socket.india.delta.exchange');assert.deepEqual(ws.sent[1].payload.channels.map(c=>c.name),['ob_l1','candlestick_5m']);const quote={type:'ob_l1',sy:'BTCUSD',ts:s.time*1000,bp:'100',ap:'101'};ws.emit(quote);ws.emit({...quote,bp:'999'});ws.emit({...quote,sy:'ETHUSD'});ws.emit({type:'candlestick_5m',res:'5m',sy:'BTCUSD',ts:s.time*1000,cst:1800000000,o:100,h:102,l:99,c:101,v:10});s.advance(1000);ws.emit({type:'candlestick_5m',res:'5m',sy:'BTCUSD',ts:s.time*1000,cst:1800000000,o:100,h:103,l:99,c:102,v:12});s.advance(1000);assert.equal(s.output.at(-1).quote.bid,100);assert.equal(s.output.at(-1).candles.filter(c=>c.timestamp===1800).length,1);assert.equal(s.output.at(-1).candles.at(-1).close,102);assert.equal(s.output.at(-1).candles.at(-1).is_forming,true);s.feed.stop();assert.equal(s.tasks.size,0);});
test('reconnect backoff resubscribes, recovers history, old socket cannot change selected stream',async()=>{const s=setup(),old=s.sockets[0];old.open();await new Promise(setImmediate);old.close();s.advance(1000);const next=s.sockets[1];next.open();await new Promise(setImmediate);assert.equal(s.recoveries,2);old.emit({type:'ob_l1',sy:'BTCUSD',ts:s.time*1000,bp:1,ap:2});assert.equal(s.feed.snapshot().quoteAt,0);assert.match(next.sent[1].payload.channels[1].name,/5m/);s.feed.stop();s.advance(60000);assert.equal(s.sockets.length,2);});
test('stale and heartbeat loss are reported; a candle boundary requests REST repair',async()=>{const s=setup(),ws=s.sockets[0];ws.open();await new Promise(setImmediate);ws.emit({type:'ob_l1',sy:'BTCUSD',ts:s.time*1000,bp:100,ap:101});s.advance(20000);assert.ok(s.health.some(h=>h.includes('stale')));s.advance(20000);assert.ok(s.health.some(h=>h.includes('heartbeat lost')));s.feed.stop();const b=setup();b.sockets[0].open();await new Promise(setImmediate);b.advance(300000);await new Promise(setImmediate);assert.ok(b.recoveries>1);b.feed.stop();});
test('Wilder RSI display SMA/EMA equals backend on completed bars and forming bar cannot alter completed indicators',()=>{const {displayRows}=require('../ema-cloud-chart.js'),{execFileSync}=require('node:child_process');const rows=Array.from({length:100},(_,i)=>({timestamp:300*(i+1),open:100+Math.sin(i)*10,high:111,low:89,close:100+Math.sin(i)*10,volume:1,is_forming:i===99}));for(const ma of ['SMA','EMA']){const py=JSON.parse(execFileSync('.venv/bin/python',['-c',"import json,sys;from strategies.ema_crossover.signals import rsi_sma_series;d=json.load(sys.stdin);print(json.dumps(rsi_sma_series(d['rows'],14,9,d['ma'])))"],{input:JSON.stringify({rows,ma}),encoding:'utf8'}));const js=displayRows(rows.filter(r=>!r.is_forming),10,30,14,9,ma);assert.ok(Math.abs(js.at(-1).rsi-py.at(-1).rsi)<1e-10);assert.ok(Math.abs(js.at(-1).rsiMa-py.at(-1).rsi_ma)<1e-10);}});
