const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function setup(){
 const nodes=new Map(),calls=[];let html='';
 function node(id){if(!nodes.has(id))nodes.set(id,{value:'',disabled:false,textContent:'',style:{},events:{},classList:{contains:()=>false},addEventListener(n,f){this.events[n]=f},replaceChildren(){},append(){},add(){},insertAdjacentHTML(pos,s){html+=s}});return nodes.get(id)}
 const status={credentials:'MISSING',authentication:'MISSING',live_gate_enabled:true,running:false,paper:{trades:[],position:null},orders:[],runner:{message:'Stopped'}};
 const context={window:{},document:{querySelector:node,getElementById:node,head:{append(){}},createElement:()=>node(Math.random())},setInterval(){},crypto:{randomUUID:()=> 'uuid-123456789'},URLSearchParams,fetch:async(url,opts)=>{calls.push({url,body:opts?JSON.parse(opts.body):undefined});return {ok:true,json:async()=>url.endsWith('status')?status:{status:'closed',filled_contracts:1}}}};
 vm.runInNewContext(fs.readFileSync('delta-india.js','utf8'),context);context.window.DeltaIndiaWorkspace.mount('other');
 for(const [k,v] of Object.entries({'workflow':'LIVE','symbol':'BTCUSD','side':'buy','contracts':'3','price':'84250','tif':'ioc','reduce':'false','timeframe':'5m','rsi':'14','ma-length':'14','ma':'SMA','direction':'BOTH'}))node('delta-'+k).value=v;
 return {node,calls,html};
}
test('LIVE Submit sends one direct explicit order with native contracts and limit',async()=>{const s=setup();await s.node('delta-submit').events.click();const submitted=s.calls.filter(c=>c.url.endsWith('/submit'));assert.equal(submitted.length,1);assert.equal(submitted[0].body.mode,'LIVE');assert.equal(submitted[0].body.contracts,3);assert.equal(submitted[0].body.limit_price,'84250');assert.equal(submitted[0].body.request_id,'uuid-123456789');assert.ok(!s.calls.some(c=>/preview|verify|confirm/.test(c.url)));});
test('runner start transmits exact selected strategy and does not automatically start at mount',async()=>{const s=setup();assert.equal(s.calls.length,0);await s.node('delta-start').events.click();assert.equal(s.calls[0].url,'/api/delta-india/runner-start');assert.equal(s.calls[0].body.resolution,'5m');assert.equal(s.calls[0].body.direction,'BOTH');});
test('connection fields are masked and cleared before request with no browser storage',async()=>{const s=setup();s.node('delta-key').value='fake-existing-key';s.node('delta-secret').value='fake-existing-secret';await s.node('delta-connect').events.click();assert.equal(s.node('delta-secret').value,'');assert.equal(s.calls[0].url,'/api/delta-india/connect');assert.ok(s.html.includes('type="password"'));assert.ok(!fs.readFileSync('delta-india.js','utf8').includes('localStorage'));});
test('order ticket precedes chart, has quantity and direct actions with responsive status',()=>{const s=setup();assert.ok(s.html.indexOf('id="delta-ticket-panel"')<s.html.indexOf('id="delta-chart"'));for(const label of ['Quantity · contracts','Submit Order','Start Runner','Connection settings'])assert.ok(s.html.includes(label));assert.ok(!/Review|Confirm|Prepare/.test(s.html));});
