"""Render the saved research results as a self-contained readable HTML report."""
import csv,json,html,statistics
from pathlib import Path
OUT=Path(__file__).resolve().parent
def read(name):return list(csv.DictReader((OUT/name).open()))
def table(rows,keys):
 return '<table><thead><tr>'+''.join('<th>'+html.escape(k.replace('_',' '))+'</th>' for k in keys)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+html.escape(str(r.get(k,'')))+'</td>' for k in keys)+'</tr>' for r in rows)+'</tbody></table>'
def main():
 sample=json.loads((OUT/'sample_final.json').read_text());prep=json.loads((OUT/'prepare_summary.json').read_text());results=read('results_final.csv');coverage=read('option_coverage_final.csv');plateaus=read('plateaus.csv');cases=json.loads((OUT/'case_results.json').read_text());selection=json.loads((OUT/'development_selection.json').read_text())
 names={'baseline':'Existing exits','current_0.1':'Current 10% sampled premium trail','structure_1_3_0.5':'1m swing + 3 ATR / 0.5 ATR buffer','structure_5_3_0.5':'5m swing + 3 ATR / 0.5 ATR buffer','hybrid_0.25_3_0.5_0.6':'5m + 25% activation / 60% gain retention','hybrid_0.05_3_0.5_0.6':'5m + 5% activation / 60% gain retention'}
 headline=[]
 for slip in ('0','0.01'):
  for x in results:
   if x['arm']=='preserve_exits' and x['split']=='heldout' and x['slippage']==slip and x['variant'] in names:
    headline.append({'candidate':names[x['variant']],'adverse_price_per_side':slip,**{k:x[k] for k in ('trades','net_points','mean_net_pct','drawdown_points','mean_giveback_pct','mean_profit_giveback_pct','early_exits','activated','baseline_preempted','continuations')}})
 plateau=[x for x in plateaus if x['arm']=='preserve_exits' and x['slippage']=='0.01' and x['split']=='heldout']
 chosen=[dict(arm=x['arm'],family=x['family'],development_selected=x['development']['variant'],development_net=x['development']['net_points'],heldout_net=x['heldout']['net_points'],heldout_trades=x['heldout']['trades']) for x in selection]
 open_case=json.loads((OUT/'open_case.json').read_text()); depth=(open_case.get('quote_response') or {}).get('d',{}).get('MCX:CRUDEOIL26OCT8600PE',{});bid=(depth.get('bids') or [{}])[0].get('price')
 case_rows=[x for x in cases if 100<=x['actual_paper_gross']<=125 or 2000<=x['actual_paper_gross']<=2250]
 paths=[x for x in read('path_sensitivity_final.csv') if x['split']=='heldout' and x['slippage']=='0.01']
 replacement=[x for x in results if x['arm']=='replace_EMA_research_only' and x['split']=='heldout' and x['slippage']=='0.01' and x['variant'] in names]
 dev=[x for x in results if x['arm']=='preserve_exits' and x['slippage']=='0.01' and x['split']=='development' and x['variant'] in names]
 months=[x for x in results if x['arm']=='preserve_exits' and x['slippage']=='0.01' and x['split'].startswith('2026-') and x['variant'] in names]
 total=sum(int(x['raw']) for x in coverage);zero=sum(int(x['zero_volume']) for x in coverage)
 body=f'''<h1>Sector Pulse trailing-exit research</h1><p class="lead">No exit is established as optimal. A five-minute structure stop plus a separate executable-premium gain floor is a defensible research shortlist, but this study does not establish reliable out-of-sample improvement or a production parameter choice.</p>
 <p>Research snapshot: 7 October 2026 IST. No orders, authentication changes, settings changes, runner restart or deployment. Current one-minute entries remain fixed within each comparison. The glowing LED and supply/demand UI are outside this work.</p>
 <h2>The reported givebacks require much earlier protection</h2><p>The journal has a Paper close of ₹120 at 22:29 IST and another of ₹2,180 at 21:43 IST on 7 October. They are plausible matches to the user's ₹1,300–1,400 → ₹120 and ₹4,000 → about ₹2,000 reports. The close amounts are recorded Paper gross P&amp;L, not exchange-confirmed Live executions or verified after-cost returns. Exact displayed peaks remain user-reported.</p>
 {table(case_rows,['symbol','entry_time','exit_time','actual_paper_gross','peak_interior_close_gross','overlapping_candle_high_upper_bound_gross','upper_bound_gain_pct','gain_required_20pct','highest_next30m_close'])}
 <p>The ₹120 trade invested ₹51,720 (258.6 × 200 effective units). A reported ₹1,300–1,400 peak is only 2.51–2.71% premium gain; 20% activation requires ₹10,344 gross gain. The ₹2,180 trade invested ₹55,340; a reported ₹4,000 peak is 7.23%, and 20% activation requires ₹11,068. Neither reported case is protected by 20/25/30% activation.</p>
 <p>Interior one-minute trade closes give a ₹680 peak for the first trade and ₹4,940 for the second; overlapping candle highs give upper bounds of ₹1,600 and ₹5,080. The boundary candles can include pre-fill or post-exit ticks. None of these is an exact executable-bid exposure peak. The second contract's next-30-minute highest observed close, 289.9, was below its in-position observed close peak, 301.4. The first case's follow-up was truncated at the collection time; its observed subsequent maximum was 259.0. This does not prove there was no later continuation.</p>
 <p>The existing 10% best-premium distance is also wide for these gains: at an illustrative 3.09% peak gain its stop would remain about 7.22% below entry; at a 9.18% peak it remains about 1.74% below entry. It is not equivalent to retaining 90% of earned profit. The case close-only 60%-gain floor at 2.5%/5% activation did not materially rescue these outcomes: the first missed the intraminute peak entirely; the second acted at the baseline exit minute. Tick resolution is central to this problem.</p>
 <h2>Open Paper position: separate evidence</h2><p>The user screen report at about 22:47 IST showed entry 263.30, quantity 2, open before-cost profit ₹3,880, realized run ₹120 and total run ₹4,000. After-cost values were unavailable. The open position's recorded multiplier is 100, so the open premium gain was about 7.37%, independently of the total-run figure.</p><p>A separate read-only probe at {open_case['captured_at']} confirmed this exact open bought-put position, with trailing disabled and no saved trailing state. The FYERS depth response showed top bid {bid} with two contracts available at that level; its recent trade timestamp was about one second old. At bid 288.3 the arithmetic open liquidation value implies ₹5,000 gross gain (about 9.49% premium gain), plus the prior ₹120 run realization. This was a quote snapshot, not a fill, locked profit or guaranteed executable price later.</p><p>At the user-reported ₹3,880 gain, illustrative retention of 40/60/80% of earned gross profit corresponds to premium floors 271.06 / 274.94 / 278.82 before tick rounding, fees and gaps. At the later ₹5,000 quote snapshot those illustrative floors would be 273.30 / 278.30 / 283.30. These are research counterfactuals, not orders or recommended settings; tighter retention exits more ordinary retracements. A 20% activation would require ₹10,532 open gross gain and would not be armed at either snapshot. Do not use total-run P&amp;L to activate a position-specific trail.</p><h2>Source findings</h2><p>The owning source was inspected in /Users/pinaki/trading/sector-heatmap/strategies/renko_supertrend/, then copied into an immutable research snapshot. trailing_stop.py defaults to OPTION_PREMIUM_PERCENT distance 10; bought options use the executable bid, initialize on fresh post-fill data, track the best bid, never loosen, and request a full-position exit. There is no premium gain activation or five-minute swing basis. The current recorded crude config has trailing disabled, EMA10 enabled, intrabar entries disabled, retest/RSI-slope enabled, and a 23:30 MCX intraday deadline.</p>
 <p>EMA10 adverse confirmed close, opposite confirmed Supertrend reversal and session boundary remain in preserved-exit arms. Configured hard stop/target are blank in this snapshot. The optional Sideways quick-loss control is an after-close re-entry lock; it is not a separate quick-loss exit. The lock records the actual-exposure underlying range after an estimated after-cost losing trade spanning at most three host candles. Historical entry construction approximates this with gross underlying losses and OHLC exposure extrema because historical executable option P&amp;L and tick ranges are absent. It cannot claim exact runner parity.</p>
 <h2>Coverage and sample</h2><p>FYERS returned {prep['raw']:,} fixed October crude futures one-minute candles from {prep['first']} through {prep['last']}, over {prep['days']} observed sessions. Three malformed OHLC rows were quarantined, leaving {prep['valid']:,}. One-minute source signals generated {sample['entries']:,} baseline entry opportunities without inventing a daily trade quota; actual max-trades limits apply to an armed run and are not reconstructible across history.</p>
 <p>Nearest unexpired expiry and nearest strike were selected from FYERS expired July/August/September catalogs and the current October master, with lower-strike/symbol ties. {len(coverage)} exact contract histories contain {total:,} returned option candles, including {zero:,} zero-volume candles. These are actual option trade-price data, not synthetic option prices. Historical listing timestamps and past lot/multiplier master snapshots are unavailable. October futures signal candles are held fixed even when earlier-expiry option deliverable futures differ; basis/roll effects limit economic interpretation.</p>
 <p>The preserved-exit common sample is {sample['eligible']:,} trades; {sample['excluded']:,} entries were excluded for missing, zero-volume or noncontiguous data, including four zero-duration cutoff episodes. The separate hypothetical EMA replacement sample is {sample['replacement_eligible']:,} because it needs longer coverage. Compare candidates within the same arm only. This exclusion creates liquidity and availability selection bias and the option sample is not representative of every underlying entry.</p>
 <p>Chronological development: {sample['development_days'][0]}–{sample['development_days'][-1]}. Heldout: {sample['heldout_days'][0]}–{sample['heldout_days'][-1]}. Monthly breakdowns are provided; July–October is not multi-year regime coverage. This crude-oil study does not establish behavior for NIFTY/SENSEX or other options markets. There is no rolling optimization/retraining claim. Parameter selection uses development results only, then reports heldout results. Intermediate results were inspected while improving coverage, so this is chronologically separated evaluation rather than a pristine preregistered trial.</p>
 <h2>What was tested</h2><p>{sample['variants']} exit parameter variants × two interaction arms × four price-cost sensitivities = {sample['runs']:,} primary runs, plus 48 prespecified intrabar-path sensitivity runs. Entry times, direction and exact contract remain frozen. Preserved arms allow candidates only to shorten the baseline exposure. EMA replacement arms retain opposite reversal and the session boundary and terminate at the next frozen entry to prevent overlapping exposure; this is a research attribution horizon, not production behavior.</p>
 <p>Current sampled trail distances: 6/8/10/12/15% of best premium. Structure candidates: confirmed one-minute or five-minute 2-left/2-right pivots, a 0.25/0.5/1 ATR(14) pivot buffer and a 2/3/4 ATR volatility envelope from the favorable close. The tighter available stop wins and never loosens. Five-minute bars require all five contiguous one-minute bars and are available only at completion. A pivot waits for two right-hand completed bars: at least ten minutes of confirmation on the five-minute frame. Prior confirmed structure can be used immediately; a new post-entry swing cannot be known immediately.</p>
 <p>Hybrid candidates use five-minute structure plus a bought-option floor of entry + 40/60/80% of peak gain, armed at 20/25/30% premium gain. Separate exploratory activation levels 2.5/5/10% address the scale of the journal cases; they are not approved settings. Primary premium decisions use completed option closes as bid proxies; execution occurs at the next observed open. This is deliberately different from the real tick trail. High→low and low→high bar paths are sensitivity scenarios, not recovered market paths; both still use next-open fills. No same-bar perfect stop execution is assumed.</p>
 <p>Cost model: ₹40 per round trip at a hypothetical 200 effective units plus 0.1% of each side's premium turnover, and adverse price adjustment of 0/0.5/1/2% per side. FYERS currently lists flat ₹20 per option order; the aggregate 0.1% allowance is a sensitivity, not a verified MCX tax schedule. Past fees/lot multipliers and bid/ask spreads are unverified. Net-point sums and drawdown are hypothetical equal-unit premium-point totals. Mean profit giveback % averages the share of positive close-observed gain surrendered, only among trades with a positive observed gain; mean giveback % uses entry premium as denominator. Mean net % is the mean trade return on paid premium, not a compounded portfolio return. Funding, concurrent positions and fill capacity are not modeled.</p>
 <h2>Preserved exits: heldout comparison</h2>{table(headline,list(headline[0]))}
 <p>Baseline-preempted counts are cases with no candidate trigger before the baseline exit. Candidate signals on the same exit minute can change attribution without shortening exposure. Early exits require a strictly earlier fill than baseline. Continuation means the observed next 30-minute option close later exceeds the candidate-exit exposure's close-based peak by at least 5% of entry premium. This is a descriptive proxy: absent later quotes are not proof of no continuation, and the column is not an exact avoidable-exit rate.</p>
 <h2>Interpretation of the heldout result</h2><p>At 1% adverse price adjustment per side, the existing 10% sampled trail improved the heldout paired total by 28.78 premium points; 15 of 1,090 exits became earlier and two were followed by the defined strong continuation. Its day-bootstrap interval was +3.86 to +60.33 points, but development uncertainty crossed zero and the gain is modest relative to unresolved execution assumptions. It does not protect the small premium gains in the cited cases.</p><p>The representative five-minute structure setting changed no heldout exit timing: the baseline preempted it on 1,082 trades, with eight same-minute attributions. The 25% activation hybrid armed on only 14/1,090 trades and shortened seven; its paired gain was 13.45 points with a bootstrap interval touching zero. Raising activation to 20–30% is largely inactive on this one-minute strategy.</p><p>The 5% activation/60% retention hybrid improved close-only paired net by 49.85 points, but its bootstrap interval was −1.39 to +102.86. It shortened 34 exposures; 12 later exceeded the prior observed peak by 5% of entry premium. Under high→low candle paths it instead lost 227.57 points relative to baseline; low→high paths lost 50.64 points. More captured intraminute peaks armed more stops, and more normal retracements then exited. This reverses the apparent close-only advantage and is the main reason not to choose it as a proven setting.</p><p>All representative absolute heldout net totals were negative under the provisional cost model, including zero extra spread/slippage. This is not a claim that the running strategy or broad options system is unprofitable: the historical fixed-contract entry construction, eligibility selection, fees, exposure and quotes differ from execution. The study supports paired research comparisons within its assumptions, not an account-performance forecast.</p><h2>Development-selected candidates and parameter plateaus</h2>{table(chosen,list(chosen[0]))}{table(plateau,['family','variants','baseline_net','min_delta','median_delta','max_delta','positive_count','negative_count','max_activation','max_early'])}
 <p>A positive isolated heldout result does not establish a stable plateau. Favor candidates that improve neighboring settings, development and later chronological periods under plausible costs. Many 20/25/30% settings may be indistinguishable because activation never occurs; that is inactivity, not robustness. Exact setting winners must not be promoted from this grid without independent tick-level validation.</p>
 <h2>Paired uncertainty and volatility regimes</h2>{table(read("paired_uncertainty.csv"),["variant","split","paired_trades","days","delta_total","bootstrap_p025","bootstrap_p975"])}<p>Seeded 2,000-resample day-block bootstrap intervals describe uncertainty of paired net-point differences on the retained sample. They do not account for missing bid/ask, excluded liquidity, historical contract metadata errors or multiple selection. Intervals crossing zero do not show a reliable advantage.</p>{table(read("regimes.csv"),["variant","regime","trades","net_points","early_exits"])}<p>Volatility slices use only the entry-decision candle source ATR ratio (below 0.8, 0.8–1.2, above 1.2). They are observed local-volatility regimes, not a claim to cover every market regime.</p><h2>Hypothetical EMA replacement, different sample</h2>{table(replacement,['variant','trades','net_points','drawdown_points','mean_giveback_pct','mean_profit_giveback_pct','early_exits','activated','baseline_preempted','continuations'])}
 <p>This arm asks whether EMA10 prevents a slower structure trail from retaining trends. It does not authorize removing EMA10. Its next-frozen-entry horizon truncates longer runners, so it cannot establish performance of a complete replacement strategy.</p>
 <h2>Intrabar-path sensitivity</h2>{table(paths,['path_model','variant','trades','net_points','drawdown_points','early_exits','activated','continuations'])}
 <p>Differences between candle-close and path scenarios show the consequences of hidden intraminute peaks and stop timing. Neither path is executable bid/ask evidence, and these results do not bound all possible real fills.</p>
 <h2>Monthly chronology</h2>{table(months,['split','variant','trades','net_points','drawdown_points','early_exits','activated','continuations'])}
 <h2>Recommendation and missing evidence</h2><p>Do not replace the existing exits or choose an allegedly optimal trail from these results. The practical shortlist is a completed five-minute structural stop to tolerate ordinary retest wicks, plus a separate fast executable-premium gain floor to limit sharp giveback. These protect different things. Keep the premium floor monotonic, derive activation from entry premium rather than rupee P&amp;L, and measure the incremental effect while preserving EMA10. A stop can give back more than its nominal floor on gaps or poor liquidity; no method can secure the exact peak and also retain every continuation.</p>
 <p>For the specific cited trades, 20–30% activation is too late. Evaluate 2.5/5/10% activation separately on real tick data before recommending a lower threshold. Keeping 40–80% of achieved gain is a research range, not a guarantee or chosen setting. Five-minute confirmation alone is too slow for a three-minute exposure with an intraminute peak.</p>
 <p>Needed for a defensible implementation choice: synchronized executable bid/ask ticks with depth for exact selected contracts, quote receipt and exchange timestamps, actual exposure/fill timestamps, historical listing/expiry/lot/multiplier metadata, the correct deliverable underlying at each expiry, and verified MCX fees. Obtain 6–12 months across expiries and varied trends/chop/volatility, then reserve later untouched periods and repeat walk-forward tests. Validate early exits followed by continuation, profit-floor breaches and gap/spread stress. Tick-level case studies must reproduce the user's displayed P&amp;L basis before calling a peak verified.</p>
 <h2>Reproduction and verification</h2><p>Offline: python prepare.py; python research.py; python summarize.py; python uncertainty.py; python case_analysis.py; python case_counterfactuals.py; python report.py. Tests: python -m unittest discover -p test_research.py. Seven deterministic tests passed: completed five-minute availability, incomplete-bar rejection, prefix/no-future invariance, monotonic bought-put bid trail, malformed OHLC rejection, zero-duration exposure rejection and next-open fill. Raw replies, fixed config, source snapshot and SHA256 manifest remain in this folder. CSVs contain full results and representative per-trade ledgers.</p>
 <p>Source documentation: <a href="https://github.com/FyersDev/fyers-c-sdk/blob/master/README.md">FYERS official SDK expired F&amp;O history endpoints</a>; <a href="https://fyers.in/charges-list">FYERS charges</a>. The read-only MCP history call initially lacked a connector token; existing application credentials provided history successfully, without authentication changes. Older help articles denying expired history conflict with the newer SDK and the successful endpoint responses; no blanket unavailability claim is made.</p>'''
 css='body{font:16px/1.6 system-ui,sans-serif;color:#202834;background:#fafafa;margin:40px auto;max-width:1180px;padding:0 24px}h1{font-size:34px}h2{margin-top:40px;font-size:23px}.lead{font-size:20px;font-weight:600}table{display:block;overflow:auto;border-collapse:collapse;background:white;width:100%;font-size:13px}th,td{padding:9px 12px;border:1px solid #dfe4ea;text-align:right;white-space:nowrap}th{background:#eaf0f7;text-align:left}a{color:#1854a0}'
 (OUT/'report.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sector Pulse trailing-exit research</title><style>'+css+'</style><body>'+body+'</body></html>')
 print('report.html generated')
if __name__=='__main__':main()
